spring.application.name=pet-api
server.port=8080

petstore.api.base-url=https://petstore.swagger.io/v2
petstore.api.connect-timeout=3s
petstore.api.read-timeout=5s

logging.level.com.marquina.pet_api=DEBUG
logging.pattern.level=%5p [txId=%X{transactionId:-}]
