spring.application.name=pet-api
server.port=${SERVER_PORT:8080}

petstore.api.base-url=${PETSTORE_API_BASE_URL:https://petstore.swagger.io/v2}
petstore.api.pet-path=/pet
petstore.api.pet-by-id-path=/pet/{petId}
petstore.api.connect-timeout=${PETSTORE_API_CONNECT_TIMEOUT:3s}
petstore.api.read-timeout=${PETSTORE_API_READ_TIMEOUT:5s}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

logging.level.com.marquina.pet_api=${LOG_LEVEL:INFO}
logging.pattern.level=%5p [txId=%X{transactionId:-}]
